### ISSUE TITLE
Activity 传值的时候不支持 Intent 吗

### ISSUE THREAD

**Issue by ssyijiu** [Xiao187/Ablepsia#1]
看了下代码 Ablepsia.kv(key,value) 放进了一个 new Intent() 中，Ablepsia 不支持直接传 Intent 吗?

**Comment by Xiao187** [comment]
sorry，几天没关注，不能直接给Intent，kv()方法就是为了简化每次都new Intent，kv()方法等同于intent.put()方法

2016-12-01 18:16 GMT+08:00 书生依旧 <notifications@github.com>:

**Comment by Xiao187** [comment]
更新了代码，增加了 kvFromIntent() 方法，并增加源代码注释
